# Generated by Django 3.2.6 on 2023-09-17 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_remove_location_vaccination_center'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='location',
            table='Location',
        ),
    ]
