# Generated by Django 4.2.5 on 2023-09-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChildGuardianManager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardian',
            name='fingerprint',
        ),
        migrations.AddField(
            model_name='guardian',
            name='fingerprint_data',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
