# Generated by Django 4.2.5 on 2023-09-24 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('child', '0001_initial'),
        ('vaccine', '0002_alter_vaccine_name_alter_vaccine_recommended_dose_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Immunization_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_administration', models.DateTimeField(auto_now_add=True)),
                ('next_date_of_administration', models.DateTimeField(auto_now=True)),
                ('child', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='child.child')),
                ('vaccine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vaccine.vaccine')),
            ],
        ),
    ]
