# Generated by Django 3.2.6 on 2023-09-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Immunization_Record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immunization_record',
            name='next_date_of_administration',
            field=models.DateField(),
        ),
    ]
