# Generated by Django 4.2.5 on 2023-09-27 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0001_initial'),
        ('Immunization_Record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='immunization_record',
            name='guardian',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='child.guardian'),
        ),
    ]
