# Generated by Django 4.2.5 on 2023-09-25 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0002_remove_child_guardian_guardian_child'),
        ('Immunization_Record', '0002_alter_immunization_record_next_date_of_administration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immunization_record',
            name='child',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='immunization_record', to='child.child'),
        ),
    ]
