# Generated by Django 3.2.6 on 2023-09-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthworker',
            name='email',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
