# Generated by Django 4.2.5 on 2023-09-25 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthworker',
            name='phone_number',
        ),
    ]
