# Generated by Django 4.2.5 on 2023-09-26 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('registration', '0002_remove_healthworker_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthworker',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.location'),
        ),
    ]
