# Generated by Django 3.2.6 on 2023-09-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20230924_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='healthworker',
            name='email',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='healthworker',
            name='first_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='healthworker',
            name='hospital',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='healthworker',
            name='last_name',
            field=models.CharField(max_length=32),
        ),
    ]
