# Generated by Django 3.2.6 on 2023-09-26 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_location_region'),
        ('registration', '0006_alter_healthworker_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthworker',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.location'),
        ),
    ]
