# Generated by Django 3.2.6 on 2023-09-26 06:46

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_location_region'),
        ('child', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.location'),
        ),
        migrations.AddField(
            model_name='child',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='child',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='guardian',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='child',
            name='guardian',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='child.guardian'),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.location'),
        ),
    ]
