# Generated by Django 4.2.5 on 2023-09-27 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='location',
        ),
        migrations.RemoveField(
            model_name='child',
            name='phone_number',
        ),
    ]
