# Generated by Django 3.2.6 on 2023-10-06 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='position',
        ),
        migrations.AddField(
            model_name='child',
            name='next_date_of_administration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='guardian',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='child.guardian'),
        ),
    ]
