# Generated by Django 4.2.5 on 2023-09-27 08:09

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('child', '0002_remove_child_location_remove_child_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.location'),
        ),
        migrations.AddField(
            model_name='child',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='2+52615152026', max_length=128, region='IR', unique=True),
        ),
    ]
