# Generated by Django 4.2.5 on 2023-09-25 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('child', '0002_remove_child_guardian_guardian_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.location'),
        ),
    ]
