# Generated by Django 3.2.6 on 2023-09-26 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_location_region'),
        ('child', '0002_auto_20230926_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.location'),
        ),
    ]
