# Generated by Django 4.2.5 on 2023-09-27 08:12

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0003_child_location_child_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IR', unique=True),
        ),
    ]
