# Generated by Django 3.2.6 on 2023-09-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Healthcare', '0002_auto_20230909_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthworker',
            name='middle_name',
            field=models.CharField(default='abdi', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='healthworker',
            name='default_country_code',
            field=models.CharField(default='+252', max_length=6),
        ),
        migrations.AlterField(
            model_name='healthworker',
            name='local_phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
