# Generated by Django 3.2.6 on 2023-09-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Healthcare', '0003_auto_20230909_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthworker',
            name='local_phone_number',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
