# Generated by Django 3.2.6 on 2023-09-09 17:14

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Healthcare', '0005_alter_healthworker_local_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthworker',
            name='default_country_code',
        ),
        migrations.AlterField(
            model_name='healthworker',
            name='local_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IR', unique=True),
        ),
    ]
