# Generated by Django 3.2.6 on 2023-09-09 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Healthcare', '0006_auto_20230909_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthworker',
            old_name='local_phone_number',
            new_name='phone_number',
        ),
    ]
