# Generated by Django 3.2.6 on 2023-09-10 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Healthcare', '0007_rename_local_phone_number_healthworker_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthworker',
            old_name='hospital_name',
            new_name='hospital',
        ),
    ]
