# Generated by Django 4.2.5 on 2023-09-11 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Healthcare", "0008_rename_hospital_name_healthworker_hospital"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="healthworker",
            name="location",
        ),
    ]
